# inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake


AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: true
  AllowedMethods: [play]

Metrics/AbcSize:
  AllowedMethods: [play]
  Max: 20
